{% set name = "CAMPneu" %}
{% set version = "1.1.0" %}
 
package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  path: ../
  #git_rev:
  #git_url: https://github.com/appliedbinf/CAMPneu.git
 
build:
  number: 1
  skip: True  # [win]

requirements:
  host:
    - python
    - pip

  run:
    - python <3.11
    - minimap2==2.28
    - samtools
    - fastp
    - fastANI
    - bcftools
    - kraken2
    - unicycler
    - freebayes
 
test:
  commands:
    - minimap2 -h

# build:#   noarch: python

 
about:
  home: https://github.com/appliedbinf/CAMPneu/
  license: MIT